version: '3.8'
services:
  app:
    build: .
    ports:
      - "443:443"
    env_file: .env
    environment:
      - MYSQL_HOST=mysql
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend

  mysql:
    image: mysql:8.0
    env_file: .env
    ports:
      - "3306:3306"
    environment:
     - MYSQL_DATABASE=${DB_DATABASE}
     - MYSQL_USERNAME=${DB_USERNAME}
     - MYSQL_PASSWORD=${DB_PASSWORD}
     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - backend
    security_opt:
      - no-new-privileges:true

volumes:
  mysql_data:
networks:
  backend:
    driver: bridge