/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NutAvatar: typeof import('nutui-uniapp/components/avatar/avatar.vue')['default']
    NutBadge: typeof import('nutui-uniapp/components/badge/badge.vue')['default']
    NutButton: typeof import('nutui-uniapp/components/button/button.vue')['default']
    NutCell: typeof import('nutui-uniapp/components/cell/cell.vue')['default']
    NutCellGroup: typeof import('nutui-uniapp/components/cellgroup/cellgroup.vue')['default']
    NutCheckbox: typeof import('nutui-uniapp/components/checkbox/checkbox.vue')['default']
    NutDivider: typeof import('nutui-uniapp/components/divider/divider.vue')['default']
    NutEllipsis: typeof import('nutui-uniapp/components/ellipsis/ellipsis.vue')['default']
    NutEmpty: typeof import('nutui-uniapp/components/empty/empty.vue')['default']
    NutForm: typeof import('nutui-uniapp/components/form/form.vue')['default']
    NutFormItem: typeof import('nutui-uniapp/components/formitem/formitem.vue')['default']
    NutGrid: typeof import('nutui-uniapp/components/grid/grid.vue')['default']
    NutGridItem: typeof import('nutui-uniapp/components/griditem/griditem.vue')['default']
    NutIcon: typeof import('nutui-uniapp/components/icon/icon.vue')['default']
    NutInput: typeof import('nutui-uniapp/components/input/input.vue')['default']
    NutInputNumber: typeof import('nutui-uniapp/components/inputnumber/inputnumber.vue')['default']
    NutNavbar: typeof import('nutui-uniapp/components/navbar/navbar.vue')['default']
    NutPopup: typeof import('nutui-uniapp/components/popup/popup.vue')['default']
    NutPrice: typeof import('nutui-uniapp/components/price/price.vue')['default']
    NutSwipe: typeof import('nutui-uniapp/components/swipe/swipe.vue')['default']
    NutSwiper: typeof import('nutui-uniapp/components/swiper/swiper.vue')['default']
    NutSwiperItem: typeof import('nutui-uniapp/components/swiperitem/swiperitem.vue')['default']
    NutSwitch: typeof import('nutui-uniapp/components/switch/switch.vue')['default']
    NutTextarea: typeof import('nutui-uniapp/components/textarea/textarea.vue')['default']
    VipTag: typeof import('./src/components/VipTag.vue')['default']
  }
}
